import type { StadiumConfig } from '../types/stadium.types';

/**
 * All distances are metres and all angles are degrees.
 *
 * Source-backed facts and calibration estimates deliberately coexist here.
 * Every non-trivial value is classified in `verification`; configurable
 * estimates must not be presented as surveyed architectural measurements.
 */
export const radesStadiumConfig = {
  version: 'rades-procedural-2',
  identity: {
    name: 'Stade Olympique Hammadi-Agrebi',
    timezone: 'Africa/Tunis',
    latitude: 36.74777,
    longitude: 10.27281,
    // Derived from the mapped pitch long axis. This is not a surveyed bearing.
    northRotationDegrees: -75.2,
    statedCapacity: 60_000,
  },
  pitch: {
    length: 105,
    width: 68,
    lineWidth: 0.12,
    centerCircleRadius: 9.15,
    penaltyAreaLength: 16.5,
    penaltyAreaWidth: 40.32,
    goalAreaLength: 5.5,
    goalAreaWidth: 18.32,
    penaltySpotDistance: 11,
    cornerArcRadius: 1,
    goalWidth: 7.32,
    goalHeight: 2.44,
    goalDepth: 2,
    mowingStripeCount: 12,
  },
  track: {
    laneCount: 10,
    laneWidth: 1.22,
    straightLength: 84.39,
    innerCurveRadius: 36.5,
  },
  tiers: [
    {
      id: 'lower',
      name: 'Lower tier',
      sectionCount: 32,
      rowCount: 28,
      startRadiusX: 96,
      startRadiusZ: 60,
      baseHeight: 2,
      rowDepth: 0.82,
      rowHeight: 0.42,
      aisleWidth: 1.4,
      walkwayWidth: 2.4,
      vomitoryEverySections: 2,
      vomitoryRow: 11,
      vomitoryWidth: 3.2,
      vomitoryHeight: 2.6,
      // Curved terraces behind both goals; angular boundaries need plans.
      seatlessSectionIndices: [0, 1, 2, 13, 14, 15, 16, 17, 18, 29, 30, 31],
    },
    {
      id: 'upper',
      name: 'Upper tier',
      sectionCount: 32,
      rowCount: 25,
      startRadiusX: 122,
      startRadiusZ: 86,
      baseHeight: 18.5,
      rowDepth: 0.86,
      rowHeight: 0.46,
      aisleWidth: 1.5,
      walkwayWidth: 2.8,
      vomitoryEverySections: 2,
      vomitoryRow: 8,
      vomitoryWidth: 3.4,
      vomitoryHeight: 2.8,
      seatlessSectionIndices: [0, 1, 2, 13, 14, 15, 16, 17, 18, 29, 30, 31],
    },
  ],
  roof: {
    innerRadiusX: 108,
    innerRadiusZ: 78,
    outerRadiusX: 154,
    outerRadiusZ: 119,
    innerHeight: 29,
    outerHeight: 33,
    panelThickness: 0.9,
    trussRadius: 0.18,
  },
  structure: {
    frameCount: 64,
    portalFrameHeight: 33,
    coveredEnclosureAreaSquareMetres: 13_000,
    exteriorRadiusOffset: 8,
    columnRadius: 0.48,
    facadeHeight: 29,
    rampCount: 8,
    rampWidth: 5.5,
    rampRun: 34,
    lightingMastCount: 4,
    lightingMastHeight: 52,
    scoreboardWidth: 14,
    scoreboardHeight: 6,
    scoreboardDepth: 1.1,
    benchLength: 8,
    benchDepth: 2.2,
    benchHeight: 2.1,
  },
  seats: {
    spacing: 0.56,
    width: 0.46,
    depth: 0.42,
    panHeight: 0.45,
    backHeight: 0.62,
    eyeHeight: 1.2,
    arcTableSamples: 1024,
  },
  occupants: {
    playerCount: 22,
    standingPlayerHeight: 1.78,
    seatedPersonHeight: 1.24,
    highQualityCrowdOccupancy: 0.7,
    lowQualityCrowdOccupancy: 0.28,
  },
  verification: {
    values: {
      'identity.latitude': 'calibrated-from-open-geodata',
      'identity.longitude': 'calibrated-from-open-geodata',
      'identity.northRotationDegrees': 'calibrated-from-open-geodata',
      'identity.statedCapacity': 'verified-from-contractor',
      'pitch.length': 'verified-from-project-brief',
      'pitch.width': 'verified-from-project-brief',
      'pitch.markings': 'estimate-requires-calibration',
      'track.laneCount': 'corroborated-secondary-source',
      'track.dimensions': 'estimate-requires-calibration',
      tiers: 'estimate-requires-calibration',
      roof: 'estimate-requires-calibration',
      'structure.frameCount': 'verified-from-contractor',
      'structure.portalFrameHeight': 'verified-from-contractor',
      'structure.coveredEnclosureAreaSquareMetres': 'verified-from-contractor',
      'structure.dimensions': 'estimate-requires-calibration',
      seats: 'estimate-requires-calibration',
      'seats.virageTerraces': 'confirmed-by-project-owner',
      'seats.virageSectionBoundaries': 'estimate-requires-calibration',
      occupants: 'estimate-requires-calibration',
    },
    notes: [
      'The contractor SBF reports 60,000 seats, a 13,000 m² covered enclosure, and 64 portal frames reaching 33 m.',
      'Coordinates and scene orientation are calibrated from OpenStreetMap geometry and still require a survey.',
      'The ten-lane track is corroborated by secondary references; its exact construction geometry requires verification.',
      'Bowl and roof radii are procedural calibration estimates chosen to clear the track and match the visible silhouette.',
      'Both virages are modeled as seatless terraces; their exact section boundaries still require seating plans.',
    ],
  },
} satisfies StadiumConfig;
