import type { StadiumConfig } from '../types/stadium.types';

/**
 * All distances are metres and all angles are degrees.
 *
 * Source-backed facts and calibration estimates deliberately coexist here.
 * Every non-trivial value is classified in `verification`; configurable
 * estimates must not be presented as surveyed architectural measurements.
 */
export const radesStadiumConfig = {
  version: 'rades-procedural-4',
  identity: {
    name: 'Stade Olympique Hammadi-Agrebi',
    timezone: 'Africa/Tunis',
    latitude: 36.74777,
    longitude: 10.27281,
    // Derived from the mapped pitch long axis. This is not a surveyed bearing.
    northRotationDegrees: -75.2,
    statedCapacity: 60_000,
  },
  pitch: {
    length: 105,
    width: 68,
    lineWidth: 0.12,
    centerCircleRadius: 9.15,
    penaltyAreaLength: 16.5,
    penaltyAreaWidth: 40.32,
    goalAreaLength: 5.5,
    goalAreaWidth: 18.32,
    penaltySpotDistance: 11,
    cornerArcRadius: 1,
    goalWidth: 7.32,
    goalHeight: 2.44,
    goalDepth: 2,
    mowingStripeCount: 12,
  },
  track: {
    laneCount: 10,
    laneWidth: 1.22,
    straightLength: 84.39,
    innerCurveRadius: 36.5,
  },
  fieldFurniture: {
    goalPostRadius: 0.06,
    goalNetGridSpacing: 0.48,
    goalNetTopDepth: 0.9,
    advertisingBoardHeight: 1,
    advertisingBoardDepth: 0.12,
    advertisingBoardSegmentLength: 5.2,
    advertisingBoardGap: 0.16,
    behindGoalOffset: 3.6,
    behindGoalRunLength: 76,
    sidelineOffset: 2.25,
    sidelineRunLength: 96,
  },
  tiers: [
    {
      id: 'lower',
      name: 'Enceinte inférieure',
      reportedCapacity: 32_000,
      sectionCount: 32,
      rowCount: 28,
      startRadiusX: 96,
      startRadiusZ: 60,
      baseHeight: 2,
      rowDepth: 0.82,
      rowHeight: 0.42,
      aisleWidth: 1.4,
      walkwayWidth: 2.4,
      vomitoryEverySections: 2,
      vomitoryRow: 11,
      vomitoryWidth: 3.2,
      vomitoryHeight: 2.6,
      vomitoryDepth: 2.4,
      vomitoryFrameThickness: 0.28,
      // Curved terraces behind both goals; angular boundaries need plans.
      seatlessSectionIndices: [0, 1, 2, 13, 14, 15, 16, 17, 18, 29, 30, 31],
    },
    {
      id: 'upper',
      name: 'Enceinte supérieure',
      reportedCapacity: 28_000,
      sectionCount: 32,
      rowCount: 25,
      startRadiusX: 122,
      startRadiusZ: 86,
      baseHeight: 18.5,
      rowDepth: 0.86,
      rowHeight: 0.46,
      aisleWidth: 1.5,
      walkwayWidth: 2.8,
      vomitoryEverySections: 2,
      vomitoryRow: 8,
      vomitoryWidth: 3.4,
      vomitoryHeight: 2.8,
      vomitoryDepth: 2.6,
      vomitoryFrameThickness: 0.3,
      seatlessSectionIndices: [0, 1, 2, 13, 14, 15, 16, 17, 18, 29, 30, 31],
    },
  ],
  bowlDetails: {
    sectionBarrierHeight: 1.05,
    sectionBarrierMidRailRatio: 0.54,
    sectionBarrierRailRadius: 0.035,
    sectionBarrierPostEveryRows: 4,
    concourseWallInset: 0.55,
    concoursePortalWidth: 5.2,
    concoursePortalHeight: 2.65,
    concoursePortalArchRise: 0.62,
    concoursePortalDepth: 0.16,
    concourseSignWidth: 0.95,
    concourseSignHeight: 0.24,
  },
  roof: {
    innerRadiusX: 108,
    innerRadiusZ: 78,
    outerRadiusX: 154,
    outerRadiusZ: 119,
    innerHeight: 29,
    outerHeight: 33,
    panelThickness: 0.9,
    trussRadius: 0.18,
    membraneBayCount: 32,
    outerWaveHeight: 0.72,
    outerWaveRadius: 0.9,
    innerTrussDepth: 3.6,
    mastCount: 8,
    mastHeight: 50,
    mastBaseOffset: 11,
    mastBaseRadius: 0.72,
    mastTopRadius: 0.2,
    mastCableRadius: 0.045,
    floodlightCount: 32,
    floodlightWidth: 3.8,
    floodlightHeight: 0.62,
  },
  structure: {
    frameCount: 64,
    portalFrameHeight: 33,
    coveredEnclosureAreaSquareMetres: 13_000,
    exteriorRadiusOffset: 8,
    columnRadius: 0.48,
    facadeHeight: 29,
    rampCount: 8,
    rampWidth: 5.5,
    rampRun: 34,
    scoreboardWidth: 14,
    scoreboardHeight: 6,
    scoreboardDepth: 1.1,
    scoreboardFlagPanelHeight: 4.6,
    benchLength: 8,
    benchDepth: 2.2,
    benchHeight: 2.1,
    benchBayCount: 8,
    benchFrameThickness: 0.08,
  },
  grandstand: {
    side: 1,
    officialCapacity: 7_000,
    pressDeskCount: 300,
    sectionIndices: [6, 7, 8, 9],
    width: 72,
    depth: 5.8,
    baseHeight: 13.8,
    height: 5.2,
    windowBayCount: 16,
    signBandHeight: 0.72,
    canopyDepth: 1.3,
    frontInset: 1.9,
  },
  exterior: {
    mainEntranceSide: 1,
    mainEntranceWidth: 76,
    mainEntranceDepth: 5.5,
    wingHeight: 18,
    centralTowerWidth: 17,
    centralTowerHeight: 24,
    archedWindowCount: 10,
    archedWindowWidth: 4.4,
    archedWindowHeight: 8.6,
    blueTrimHeight: 0.55,
    yellowBandHeight: 1.45,
  },
  seats: {
    spacing: 0.56,
    width: 0.46,
    depth: 0.42,
    panHeight: 0.45,
    backHeight: 0.62,
    eyeHeight: 1.2,
    arcTableSamples: 1024,
  },
  occupants: {
    playerCount: 22,
    standingPlayerHeight: 1.78,
    seatedPersonHeight: 1.24,
    highQualityCrowdOccupancy: 0.52,
    lowQualityCrowdOccupancy: 0.22,
  },
  verification: {
    values: {
      'identity.latitude': 'calibrated-from-open-geodata',
      'identity.longitude': 'calibrated-from-open-geodata',
      'identity.northRotationDegrees': 'calibrated-from-open-geodata',
      'identity.statedCapacity': 'verified-from-contractor',
      'pitch.length': 'verified-from-project-brief',
      'pitch.width': 'verified-from-project-brief',
      'pitch.markings': 'estimate-requires-calibration',
      'track.laneCount': 'corroborated-secondary-source',
      'track.dimensions': 'estimate-requires-calibration',
      fieldFurniture: 'estimate-requires-calibration',
      tiers: 'estimate-requires-calibration',
      'tiers.reportedCapacities': 'corroborated-secondary-source',
      bowlDetails: 'estimate-requires-calibration',
      roof: 'estimate-requires-calibration',
      'structure.frameCount': 'verified-from-contractor',
      'structure.portalFrameHeight': 'verified-from-contractor',
      'structure.coveredEnclosureAreaSquareMetres': 'verified-from-contractor',
      'structure.dimensions': 'estimate-requires-calibration',
      'grandstand.officialCapacity': 'corroborated-secondary-source',
      'grandstand.pressDeskCount': 'corroborated-secondary-source',
      'grandstand.dimensions': 'estimate-requires-calibration',
      exterior: 'estimate-requires-calibration',
      seats: 'estimate-requires-calibration',
      'seats.virageTerraces': 'confirmed-by-project-owner',
      'seats.virageSectionBoundaries': 'estimate-requires-calibration',
      occupants: 'estimate-requires-calibration',
    },
    notes: [
      'The contractor SBF reports 60,000 seats, a 13,000 m² covered enclosure, and 64 portal frames reaching 33 m.',
      'Coordinates and scene orientation are calibrated from OpenStreetMap geometry and still require a survey.',
      'The ten-lane track is corroborated by secondary references; its exact construction geometry requires verification.',
      'Bowl and roof radii are procedural calibration estimates chosen to clear the track and match the visible silhouette.',
      'Both virages are modeled as seatless terraces; their exact section boundaries still require seating plans.',
      'Published summaries split the stated capacity into 32,000 lower-tribune and 28,000 upper-tribune places; procedural chair instances intentionally do not assert those totals.',
      'Section rails, framed vomitories, and concourse openings are photo-calibrated procedural estimates.',
      'The honor stand is reported at 7,000 places and the press stand at 300 desks; their modeled envelope is photo-calibrated rather than surveyed.',
      'Goal nets, advertising hoardings, roof waves, support masts, and the ceremonial entrance are visual estimates from dated photographs and may vary by event or renovation state.',
    ],
  },
} satisfies StadiumConfig;
