import type { StadiumConfig } from '../types/stadium.types';

/**
 * All distances are metres and all angles are degrees.
 *
 * Source-backed facts and calibration estimates deliberately coexist here.
 * Every non-trivial value is classified in `verification`; configurable
 * estimates must not be presented as surveyed architectural measurements.
 */
export const radesStadiumConfig = {
  version: 'rades-procedural-20',
  identity: {
    name: 'Stade Olympique Hammadi-Agrebi',
    timezone: 'Africa/Tunis',
    latitude: 36.74777,
    longitude: 10.27281,
    // Derived from the mapped pitch long axis. This is not a surveyed bearing.
    northRotationDegrees: -75.2,
    historicalReportedCapacity: 60_000,
    currentUsableCapacity: null,
  },
  pitch: {
    length: 105,
    width: 68,
    lineWidth: 0.12,
    centerCircleRadius: 9.15,
    penaltyAreaLength: 16.5,
    penaltyAreaWidth: 40.32,
    goalAreaLength: 5.5,
    goalAreaWidth: 18.32,
    penaltySpotDistance: 11,
    cornerArcRadius: 1,
    goalWidth: 7.32,
    goalHeight: 2.44,
    goalDepth: 2,
    mowingStripeCount: 12,
  },
  track: {
    laneCount: 8,
    laneWidth: 1.22,
    straightLength: 84.39,
    innerCurveRadius: 36.5,
    innerKerbWidth: 0.18,
    drainChannelWidth: 0.12,
    // The two bends intentionally differ; all values remain visual estimates.
    eventEnds: [
      {
        id: 'west-event-end',
        side: -1,
        apronStartOffset: 3.5,
        runwayLength: 18,
        runwayWidth: 10.2,
        runwayLineCount: 6,
        runwayOffsetZ: 0,
        sandPitLength: 8.6,
        sandPitWidth: 3,
        sandPitOffsetFromPitchEnd: 8.4,
        sandPitOffsetZ: -15.4,
        throwingCircleRadius: 1.25,
        throwingCircleOffsetFromPitchEnd: 16,
        throwingCircleOffsetZ: 14,
      },
      {
        id: 'east-event-end',
        side: 1,
        apronStartOffset: 4.8,
        runwayLength: 22,
        runwayWidth: 6.4,
        runwayLineCount: 4,
        runwayOffsetZ: -7.8,
        sandPitLength: 9.2,
        sandPitWidth: 3.2,
        sandPitOffsetFromPitchEnd: 9.8,
        sandPitOffsetZ: -16,
        throwingCircleRadius: 1.35,
        throwingCircleOffsetFromPitchEnd: 14.5,
        throwingCircleOffsetZ: 12.4,
      },
    ],
    // Straight-side long-jump furniture is positioned from the supplied
    // interior model and is not based on a surveyed athletics plan.
    straightJump: {
      side: 1,
      direction: 1,
      centerX: -13,
      outsideOffset: 4.3,
      runwayLength: 40,
      runwayWidth: 1.22,
      pitLength: 9,
      pitWidth: 3,
    },
  },
  fieldFurniture: {
    goalPostRadius: 0.06,
    goalNetGridSpacing: 0.48,
    goalNetTopDepth: 0.9,
    advertisingBoardHeight: 1,
    advertisingBoardDepth: 0.12,
    advertisingBoardSegmentLength: 5.2,
    advertisingBoardGap: 0.16,
    behindGoalOffset: 3.6,
    behindGoalRunLength: 76,
    sidelineOffset: 2.25,
    sidelineRunLength: 96,
  },
  tiers: [
    {
      id: 'lower',
      name: 'Enceinte inférieure',
      historicalReportedCapacity: 32_000,
      sectionCount: 32,
      rowCount: 28,
      startRadiusX: 96,
      startRadiusZ: 60,
      baseHeight: 2,
      rowDepth: 0.82,
      rowHeight: 0.42,
      aisleWidth: 1.4,
      aisleWidthOverrides: [
        { boundaryIndex: 4, width: 2.5 },
        { boundaryIndex: 8, width: 3.4 },
        { boundaryIndex: 12, width: 2.5 },
        { boundaryIndex: 20, width: 2.5 },
        { boundaryIndex: 28, width: 2.5 },
      ],
      // Four full-depth separation corridors between the end virages and
      // lateral stands. Their dimensions remain visual estimates.
      majorCutouts: [
        {
          id: 'north-east-virage-access',
          boundaryIndex: 3,
          width: 11,
          accessWidth: 6.4,
          wallHeight: 1.55,
        },
        {
          id: 'north-west-virage-access',
          boundaryIndex: 13,
          width: 11,
          accessWidth: 6.4,
          wallHeight: 1.55,
        },
        {
          id: 'south-west-virage-access',
          boundaryIndex: 19,
          width: 11,
          accessWidth: 6.4,
          wallHeight: 1.55,
        },
        {
          id: 'south-east-virage-access',
          boundaryIndex: 29,
          width: 11,
          accessWidth: 6.4,
          wallHeight: 1.55,
        },
      ],
      walkwayWidth: 2.4,
      vomitorySectionIndices: [1, 4, 6, 9, 12, 14, 17, 20, 22, 25, 28, 30],
      vomitoryRow: 11,
      vomitoryWidth: 3.2,
      vomitoryHeight: 2.6,
      vomitoryDepth: 2.4,
      vomitoryFrameThickness: 0.28,
      vomitoryOverrides: [
        { sectionIndex: 6, row: 9, width: 4.4, height: 3 },
        { sectionIndex: 9, row: 9, width: 4.4, height: 3 },
        { sectionIndex: 22, row: 9, width: 4.4, height: 3 },
        { sectionIndex: 25, row: 9, width: 4.4, height: 3 },
      ],
      // Curved terraces behind both goals; angular boundaries need plans.
      seatlessSectionIndices: [0, 1, 2, 13, 14, 15, 16, 17, 18, 29, 30, 31],
      closedToVisitorsSectionIndices: [],
    },
    {
      id: 'upper',
      name: 'Enceinte supérieure',
      historicalReportedCapacity: 28_000,
      sectionCount: 32,
      rowCount: 25,
      startRadiusX: 122,
      startRadiusZ: 86,
      baseHeight: 18.5,
      rowDepth: 0.86,
      rowHeight: 0.46,
      aisleWidth: 1.5,
      aisleWidthOverrides: [
        { boundaryIndex: 4, width: 2.7 },
        { boundaryIndex: 8, width: 3.1 },
        { boundaryIndex: 12, width: 2.7 },
        { boundaryIndex: 20, width: 2.7 },
        { boundaryIndex: 28, width: 2.7 },
      ],
      majorCutouts: [],
      walkwayWidth: 2.8,
      vomitorySectionIndices: [
        0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
      ],
      vomitoryRow: 8,
      vomitoryWidth: 3.4,
      vomitoryHeight: 2.8,
      vomitoryDepth: 2.6,
      vomitoryFrameThickness: 0.3,
      vomitoryOverrides: [
        { sectionIndex: 6, row: 7, width: 4.8, height: 3.2 },
        { sectionIndex: 8, row: 7, width: 4.8, height: 3.2 },
        { sectionIndex: 22, row: 7, width: 4.8, height: 3.2 },
        { sectionIndex: 24, row: 7, width: 4.8, height: 3.2 },
      ],
      seatlessSectionIndices: [],
      // The upper virage remains part of the physical bowl but is not offered
      // as a public viewing location in the current operating layout.
      closedToVisitorsSectionIndices: [
        0, 1, 2, 13, 14, 15, 16, 17, 18, 29, 30, 31,
      ],
    },
  ],
  bowlDetails: {
    sectionBarrierHeight: 1.05,
    sectionBarrierMidRailRatio: 0.54,
    sectionBarrierRailRadius: 0.035,
    sectionBarrierPostEveryRows: 4,
    concourseWallInset: 0.55,
    concoursePortalWidth: 5.2,
    concoursePortalHeight: 2.65,
    concoursePortalDepth: 0.16,
    concoursePortalFrameThickness: 0.24,
    concourseFasciaHeight: 0.42,
    concourseAccentBandHeight: 0.24,
    concourseSignWidth: 0.95,
    concourseSignHeight: 0.24,
    tracksideRailInset: 0.72,
    tracksideRailHeight: 1.05,
    tracksideRailMidRatio: 0.54,
    tracksideRailRadius: 0.035,
    tracksideRailSegmentCount: 128,
  },
  roof: {
    innerRadiusX: 108,
    innerRadiusZ: 78,
    outerRadiusX: 154,
    outerRadiusZ: 119,
    innerHeight: 34.4,
    outerHeight: 33,
    panelThickness: 0.9,
    trussRadius: 0.18,
    membraneBayCount: 32,
    outerWaveHeight: 1.05,
    outerWaveRadius: 1.35,
    innerWaveHeight: 0.38,
    membraneSag: 1.45,
    innerTrussDepth: 5.2,
    mastCount: 8,
    mastHeight: 50,
    mastBaseOffset: 11,
    mastBaseRadius: 0.72,
    mastTopRadius: 0.2,
    mastCableRadius: 0.045,
    mastBackstayOffset: 34,
    floodlightCount: 64,
    floodlightWidth: 2.25,
    floodlightHeight: 0.62,
    floodlightBankCount: 16,
    floodlightsPerBank: 4,
    floodlightSpacing: 2.45,
    floodlightSupportRadius: 0.075,
    membraneSeamRadius: 0.055,
    innerFasciaHeight: 0.7,
    innerCatwalkWidth: 1.45,
    innerCatwalkHeight: 28.45,
    innerCatwalkRailHeight: 1.05,
    innerCatwalkRailSegmentCount: 64,
  },
  structure: {
    frameCount: 64,
    portalFrameHeight: 33,
    coveredEnclosureAreaSquareMetres: 13_000,
    exteriorRadiusOffset: 8,
    columnRadius: 0.48,
    facadeHeight: 29,
    rampCount: 4,
    rampWidth: 3.2,
    rampTowerRadius: 10.8,
    // Four photographed towers form two pairs along the ceremonial long side.
    rampTowerCenterXs: [-116, -86, 86, 116],
    rampTowerCenterZ: 143,
    rampTurns: 2.65,
    rampGuardHeight: 1.05,
    exteriorBraceBayCount: 32,
    exteriorBraceBottomHeight: 20,
    exteriorBraceTopHeight: 29,
    exteriorBraceRadiusOffset: 4.8,
    exteriorBandBottomHeight: 10.2,
    exteriorBandHeight: 6.3,
    exteriorPatternCount: 48,
    scoreboardWidth: 14,
    scoreboardHeight: 6,
    scoreboardDepth: 1.1,
    scoreboardSupportDrop: 3.4,
    scoreboardDeckDepth: 2.7,
    scoreboardDeckWidthMargin: 2.2,
    scoreboardDeckRailHeight: 1.05,
    benchLength: 11.4,
    benchDepth: 2.5,
    benchHeight: 2.25,
    benchBayCount: 8,
    benchFrameThickness: 0.08,
    benchSidelineOffset: 9.2,
    benchSeparation: 8.4,
    benchSeatCount: 12,
  },
  grandstand: {
    side: 1,
    officialCapacity: 7_000,
    pressDeskCount: 300,
    sectionIndices: [6, 7, 8, 9],
    vipSectionIndices: [7, 8],
    width: 90,
    depth: 5.8,
    baseHeight: 13.8,
    height: 5.2,
    windowBayCount: 24,
    facadeLevelCount: 3,
    facadeWindowHeight: 0.78,
    facadeLevelSpacing: 1.42,
    signBandHeight: 0.72,
    frontInset: 1.9,
    balconyDepth: 1.7,
    balconyRailHeight: 0.95,
    centralSuiteWidth: 24,
    centralSuiteHeight: 6.4,
    pressSuiteWidth: 16,
    pressSuiteHeight: 4.8,
    controlRoomWidth: 7,
    controlRoomHeight: 3.7,
    serviceCoreWidth: 5.5,
    serviceCoreHeight: 7.4,
    suiteGap: 1,
    upperTierSeatClearanceRows: 4,
    // The current retractable covered route was reported as roughly 30 m.
    playerTunnelLength: 30,
    playerTunnelWidth: 5.2,
    playerTunnelEaveHeight: 2.5,
    playerTunnelRidgeHeight: 3.25,
    playerTunnelFrameCount: 16,
    playerTunnelFrameRadius: 0.045,
    playerTunnelPitchClearance: 2,
    playerTunnelSeatClearanceRows: 4,
  },
  exterior: {
    mainEntranceSide: 1,
    mainEntranceWidth: 76,
    mainEntranceDepth: 5.5,
    wingHeight: 18,
    centralTowerWidth: 17,
    centralTowerHeight: 24,
    archedWindowCount: 10,
    archedWindowWidth: 4.4,
    archedWindowHeight: 8.6,
    blueTrimHeight: 0.55,
    yellowBandHeight: 1.45,
    plazaWidth: 96,
    plazaDepth: 58,
    flagpoleCount: 6,
    flagpoleHeight: 14,
    palmCount: 4,
  },
  site: {
    baseRadiusX: 235,
    baseRadiusZ: 215,
    promenadeOffset: 7,
    promenadeWidth: 13,
    landscapeWidth: 11,
    serviceRoadWidth: 22,
  },
  seats: {
    spacing: 0.56,
    width: 0.46,
    depth: 0.42,
    panHeight: 0.45,
    backHeight: 0.62,
    eyeHeight: 1.2,
    arcTableSamples: 1024,
    lowerPrimaryColor: '#33b9c4',
    lowerAccentColor: '#c8478c',
    upperPrimaryColor: '#25aebd',
    upperAccentColor: '#bd3c82',
    vipColor: '#1748b8',
    accentRowInterval: 14,
    colorSectionBandSize: 4,
  },
  occupants: {
    playerCount: 22,
    standingPlayerHeight: 1.78,
    standingSpectatorHeight: 1.72,
    seatedPersonHeight: 1.24,
    highQualityCrowdOccupancy: 0.52,
    lowQualityCrowdOccupancy: 0.14,
    crowdAnimatedFraction: 0.06,
    crowdMotionAmplitude: 0.035,
    crowdMotionCyclesPerSecond: 0.18,
    technicalAreaSeatedPerTeam: 9,
    technicalAreaStandingPerTeam: 2,
  },
  verification: {
    values: {
      'identity.latitude': 'calibrated-from-open-geodata',
      'identity.longitude': 'calibrated-from-open-geodata',
      'identity.northRotationDegrees': 'calibrated-from-open-geodata',
      'identity.historicalReportedCapacity': 'verified-from-contractor',
      'identity.currentUsableCapacity': 'confirmed-by-project-owner',
      'pitch.length': 'verified-from-project-brief',
      'pitch.width': 'verified-from-project-brief',
      'pitch.markings': 'estimate-requires-calibration',
      'track.laneCount': 'calibrated-from-authorized-visual-reference',
      'track.dimensions': 'estimate-requires-calibration',
      'track.fieldEventAprons': 'calibrated-from-authorized-visual-reference',
      fieldFurniture: 'estimate-requires-calibration',
      tiers: 'estimate-requires-calibration',
      'tiers.historicalReportedCapacities': 'corroborated-secondary-source',
      bowlDetails: 'estimate-requires-calibration',
      'bowlDetails.interiorVisualForm':
        'calibrated-from-authorized-visual-reference',
      roof: 'estimate-requires-calibration',
      'roof.visualForm': 'calibrated-from-authorized-visual-reference',
      'structure.frameCount': 'verified-from-contractor',
      'structure.portalFrameHeight': 'verified-from-contractor',
      'structure.coveredEnclosureAreaSquareMetres': 'verified-from-contractor',
      'structure.dimensions': 'estimate-requires-calibration',
      'structure.spiralRamps': 'estimate-requires-calibration',
      'structure.spiralRampArrangement':
        'calibrated-from-authorized-visual-reference',
      'structure.exteriorBracing': 'estimate-requires-calibration',
      'structure.teamBenches': 'estimate-requires-calibration',
      'structure.playerTunnelLength': 'corroborated-secondary-source',
      'structure.playerTunnelVisualForm':
        'calibrated-from-authorized-visual-reference',
      'grandstand.officialCapacity': 'corroborated-secondary-source',
      'grandstand.pressDeskCount': 'corroborated-secondary-source',
      'grandstand.dimensions': 'estimate-requires-calibration',
      exterior: 'estimate-requires-calibration',
      'exterior.visualForm': 'calibrated-from-authorized-visual-reference',
      site: 'estimate-requires-calibration',
      seats: 'estimate-requires-calibration',
      'seats.virageTerraces': 'confirmed-by-project-owner',
      'seats.virageSectionBoundaries': 'estimate-requires-calibration',
      occupants: 'estimate-requires-calibration',
    },
    notes: [
      'The contractor SBF historically reports 60,000 places, a 13,000 m² covered enclosure, and 64 portal frames reaching 33 m; the model does not assert a current usable capacity.',
      'Coordinates and scene orientation are calibrated from OpenStreetMap geometry and still require a survey.',
      'The visible eight-lane oval and straight-side jump facility are calibrated from the supplied reference model; exact athletics construction geometry still requires a survey.',
      'Bowl and roof radii are procedural calibration estimates chosen to clear the track and match the visible silhouette.',
      'The lower virages are modeled as seatless terraces; the upper virage keeps physical chairs but is closed to visitors. Exact boundaries still require seating plans.',
      'Published historical summaries split capacity into 32,000 lower-tribune and 28,000 upper-tribune places; procedural chair instances and current visitor access intentionally do not assert those totals.',
      'Section rails, framed vomitories, and concourse openings are photo-calibrated procedural estimates.',
      'The honor stand is reported at 7,000 places and the press stand at 300 desks; their modeled envelope is photo-calibrated rather than surveyed.',
      'Goal nets, advertising hoardings, roof waves, support masts, and the ceremonial entrance are visual estimates from dated photographs and may vary by event or renovation state.',
      'The paired blue technical-area shelters are positioned from interior photographs; their exact dimensions and athletics-track offsets require a site survey.',
      'Crowd and player motion is a lightweight illustrative match-day simulation, not motion-captured behavior or a reconstruction of a real match.',
      'Four circular access-ramp towers, the open X-braced upper facade, membrane seams, and suspended scoreboards are photo-calibrated visual estimates.',
      'The paired ramp arrangement, faceted roof character, and ceremonial-side massing were independently rebuilt from an authorized public visual reference; no reference mesh or texture is included.',
      'The arched concourse bays, tier-separator fascia, track-bend event aprons, inner safety rail, and denser roof-edge lattice are visually calibrated from owner-supplied reference renders; their dimensions are not surveyed.',
      'Vomitories and wide stair wedges use explicit per-section access data instead of an evenly repeated rule; their locations remain visual estimates pending seating plans.',
      'The main-stand player route includes the approximately 30 m retractable covered tunnel reported in January 2023; width, frame spacing, and exact endpoints remain visual estimates.',
      'The honor, press, control-room, and service-core volumes are modeled separately from interior references; their envelope and window rhythm remain unsurveyed estimates.',
      'The two athletics bends have independent apron, runway, sand-pit, and throwing-circle layouts derived from interior views; they are intentionally not mirrored.',
      'Seat colors use broad section and row blocks rather than a fine checkerboard, while chairless lower virages use separate standing spectator instances.',
      'The inner roof now includes an estimated maintenance catwalk, clustered floodlight banks, and scoreboard service decks visible from spectator viewpoints.',
      'The bowl, seating rows, walkways, and front safety rail now follow a rounded-stadium capsule perimeter with flat long sides instead of a continuous mathematical ellipse.',
      'Four full-depth lower-tier corridors separate the two virages from the lateral stands; the ramp widths and portal dimensions are calibrated from the supplied reference model and remain unsurveyed.',
      'Upper-virage sections remain physically modeled but are marked closed to visitors; they are excluded from public POV selection, crowds, and visitor-facing simulations.',
      'The membrane, inner truss, fascia, lighting supports, and static shadow meshes now share the rounded-stadium plan visible in the supplied interior reference; the yellow scoreboard housings and diagonal hangers are visual estimates.',
      'Repeated arched concourse bays, a continuous multi-level main-stand facade, and a blue VIP chair block are visually calibrated from the supplied interior model and remain unsurveyed.',
    ],
  },
} satisfies StadiumConfig;
